title: Antonio Muñiz
description: Devops / SRE
#remote_theme: pages-themes/hacker@v0.2.0

url: https://links.antoniomuniz.com
baseurl: ''
##############
#    TEMA    #
##############
remote_theme: hydecorp/hydejack@v9.1.6
#################
#    PLUGINS    #
#################
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-avatar
  - jekyll-feed

#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

###################
#    Menú lateral #
###################
menu:
  - title: Blog
    url:   /blog/
  - title: About
    url:   /about/


permalink: pretty
logo: /assets/img/me.jpg

paginate:      10
paginate_path: /blog/:num/ #!

author:
  name:  Antonio Muñiz  
  picture:  /assets/img/me.jpg
  about: | 
    Hola, soy Antonio y me dedico a actualizar ficheros con extensión .yml o .yaml
  social:
    twitter: Antonio_Muniz_C
    github:  amc1981
    linkedin: https://www.linkedin.com/in/antonio-mu%C3%B1iz-casado/
    email: amc1981@gmail.com

collections:
  featured_categories:
    permalink:         /blog/category/:name/
    output:            true
  featured_tags:
    permalink:         /blog/tags/:name/
    output:            true

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: featured_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: featured_tags
    values:
      layout: blog_by_tag

# Jekyll-compose configuration

jekyll_compose:
  auto_open: true
  default_front_matter:
    drafts:
      description:
      image:
      category:
      tags:
      author: Antonio
    posts:
      description:
      image:
      category:
      tags:
      author: Antonio
      published: false
      sitemap: false

# Jekyll-feed configuration

feed:
  path: /blog/feed.xslt.xml
  excerpt_only: true

