title: Donde encontrarme y en que ando cacharreando
description: Como linktree pero hecho a manili en Github pages
#remote_theme: pages-themes/hacker@v0.2.0
remote_theme: hydecorp/hydejack@v9.1.6
plugins:
  - jekyll-include-cache
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
