title: Donde encontrarme y en que ando cacharreando
description: Como linktree pero hecho a manili en Github pages
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
